# Generated by Django 5.2 on 2025-08-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome Completo')),
                ('lattes_link', models.URLField(blank=True, null=True, verbose_name='Link para Currículo Lattes')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoPaginaProducoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pagina', models.CharField(default='Produções Bibliográficas', max_length=200, verbose_name='Título da Página')),
                ('descricao_pagina', models.TextField(blank=True, help_text='Texto introdutório da página de produções bibliográficas', null=True, verbose_name='Descrição da Página')),
                ('imagem_hero', models.ImageField(blank=True, help_text='Imagem de fundo da seção hero da página de produções', null=True, upload_to='configuracao_producoes/', verbose_name='Imagem Hero')),
            ],
            options={
                'verbose_name': 'Configuração da Página de Produções',
                'verbose_name_plural': 'Configurações da Página de Produções',
            },
        ),
        migrations.CreateModel(
            name='ProducaoBibliografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título da Produção')),
                ('link_producao', models.URLField(blank=True, null=True, verbose_name='Link para a Produção')),
                ('tipo', models.CharField(choices=[('ARTIGO', 'Artigo de Periódico'), ('LIVRO', 'Livro'), ('CAPITULO', 'Capítulo de Livro'), ('ANAIS', 'Trabalho em Anais de Evento'), ('TESE', 'Tese'), ('DISSERTACAO', 'Dissertação'), ('OUTRO', 'Outro')], default='ARTIGO', max_length=20, verbose_name='Tipo de Produção')),
                ('local_publicacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local de Publicação (Revista, Livro, Anais)')),
                ('volume', models.CharField(blank=True, max_length=50, null=True, verbose_name='Volume')),
                ('numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número/Edição')),
                ('paginas', models.CharField(blank=True, max_length=50, null=True, verbose_name='Páginas (ex: 628-653)')),
                ('ano_publicacao', models.IntegerField(verbose_name='Ano de Publicação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('autores', models.ManyToManyField(related_name='producoes', to='producoes_bibliograficas.autor', verbose_name='Autores')),
            ],
            options={
                'verbose_name': 'Produção Bibliográfica',
                'verbose_name_plural': 'Produções Bibliográficas',
                'ordering': ['-ano_publicacao', 'titulo'],
            },
        ),
    ]
