# Generated by Django 5.2 on 2025-07-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pagina', models.CharField(default='Linhas de Pesquisa', max_length=200, verbose_name='Título da Página')),
                ('descricao_pagina', models.TextField(blank=True, help_text='Texto introdutório da página', null=True, verbose_name='Descrição da Página')),
                ('imagem_hero', models.ImageField(blank=True, help_text='Imagem de fundo da seção hero', null=True, upload_to='configuracao/', verbose_name='Imagem Hero')),
            ],
            options={
                'verbose_name': 'Configuração da Página',
                'verbose_name_plural': 'Configurações da Página',
            },
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Estudante')),
                ('nivel', models.CharField(choices=[('IC', 'Iniciação Científica'), ('PAVI', 'PAVI'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado')], max_length=20, verbose_name='Nível')),
                ('universidade', models.CharField(max_length=200, verbose_name='Universidade')),
                ('programa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Programa')),
                ('link_lattes', models.URLField(blank=True, null=True, verbose_name='Link do Currículo Lattes')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Estudante',
                'verbose_name_plural': 'Estudantes',
                'ordering': ['nivel', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Pesquisador')),
                ('universidade', models.CharField(max_length=200, verbose_name='Universidade')),
                ('link_lattes', models.URLField(blank=True, null=True, verbose_name='Link do Currículo Lattes')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Pesquisador',
                'verbose_name_plural': 'Pesquisadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LinhaPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título da Linha de Pesquisa')),
                ('objetivo', models.TextField(verbose_name='Objetivo')),
                ('palavras_chave', models.TextField(help_text='Separe as palavras-chave por ponto e vírgula (;)', verbose_name='Palavras-chave')),
                ('setores_aplicacao', models.TextField(verbose_name='Setores de Aplicação')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem ilustrativa da linha de pesquisa', null=True, upload_to='linhas_pesquisa/', verbose_name='Imagem')),
                ('ativa', models.BooleanField(default=True, verbose_name='Linha Ativa')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem em que a linha aparecerá na página', verbose_name='Ordem de Exibição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('estudantes', models.ManyToManyField(blank=True, to='linhas_pesquisa.estudante', verbose_name='Estudantes Relacionados')),
                ('pesquisadores', models.ManyToManyField(blank=True, to='linhas_pesquisa.pesquisador', verbose_name='Pesquisadores Relacionados')),
            ],
            options={
                'verbose_name': 'Linha de Pesquisa',
                'verbose_name_plural': 'Linhas de Pesquisa',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
