# Generated by Django 5.2 on 2025-08-07 16:27

import django.core.validators
import publicacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPaginaPublicacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pagina', models.CharField(default='Publicações', help_text='Título principal exibido na página de publicações', max_length=200, verbose_name='Título da Página')),
                ('descricao_pagina', models.TextField(blank=True, help_text='Texto descritivo exibido abaixo do título (opcional)', null=True, verbose_name='Descrição da Página')),
                ('imagem_hero', models.ImageField(blank=True, help_text='Imagem de destaque para a seção hero da página (opcional)', null=True, upload_to='publicacoes/hero/', verbose_name='Imagem Hero')),
                ('publicacoes_por_pagina', models.PositiveIntegerField(default=12, help_text='Número de publicações exibidas por página', verbose_name='Publicações por Página')),
                ('mostrar_estatisticas', models.BooleanField(default=True, help_text='Exibir seção de estatísticas na página', verbose_name='Mostrar Estatísticas')),
                ('ativa', models.BooleanField(default=True, help_text='Indica se esta configuração está ativa', verbose_name='Configuração Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração da Página de Publicações',
                'verbose_name_plural': 'Configurações da Página de Publicações',
            },
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do organizador da publicação', max_length=200, verbose_name='Nome do Organizador')),
                ('biografia', models.TextField(blank=True, help_text='Breve biografia do organizador (opcional)', null=True, verbose_name='Biografia')),
                ('lattes_link', models.URLField(blank=True, help_text='URL do currículo Lattes do organizador (opcional)', null=True, verbose_name='Link do Lattes')),
                ('email', models.EmailField(blank=True, help_text='E-mail de contato do organizador (opcional)', max_length=254, null=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o organizador está ativo no sistema', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Organizador',
                'verbose_name_plural': 'Organizadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PublicacaoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título completo da publicação', max_length=300, verbose_name='Título da Publicação')),
                ('subtitulo', models.CharField(blank=True, help_text='Subtítulo da publicação (opcional)', max_length=300, null=True, verbose_name='Subtítulo')),
                ('categoria', models.CharField(choices=[('LIVRO', 'Livro'), ('REVISTA', 'Revista'), ('ANAIS', 'Anais de Evento'), ('RELATORIO', 'Relatório'), ('MANUAL', 'Manual'), ('GUIA', 'Guia'), ('OUTROS', 'Outros')], default='LIVRO', help_text='Categoria da publicação', max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, help_text='Breve descrição ou resumo da publicação (opcional)', null=True, verbose_name='Descrição')),
                ('ano_publicacao', models.PositiveIntegerField(help_text='Ano em que a publicação foi lançada', verbose_name='Ano de Publicação')),
                ('editora', models.CharField(blank=True, help_text='Nome da editora responsável pela publicação (opcional)', max_length=200, null=True, verbose_name='Editora')),
                ('isbn', models.CharField(blank=True, help_text='Número ISBN da publicação (opcional)', max_length=20, null=True, verbose_name='ISBN')),
                ('numero_paginas', models.PositiveIntegerField(blank=True, help_text='Total de páginas da publicação (opcional)', null=True, verbose_name='Número de Páginas')),
                ('arquivo_pdf', models.FileField(help_text='Arquivo PDF da publicação (máximo 50MB)', upload_to=publicacoes.models.upload_pdf_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), publicacoes.models.validate_pdf_file], verbose_name='Arquivo PDF')),
                ('thumbnail', models.ImageField(blank=True, help_text='Miniatura da primeira página (gerada automaticamente)', null=True, upload_to=publicacoes.models.upload_thumbnail_path, verbose_name='Miniatura')),
                ('destaque', models.BooleanField(default=False, help_text='Marque para destacar esta publicação na página principal', verbose_name='Publicação em Destaque')),
                ('ativa', models.BooleanField(default=True, help_text='Indica se a publicação está visível no site', verbose_name='Ativa')),
                ('downloads', models.PositiveIntegerField(default=0, help_text='Contador de downloads da publicação', verbose_name='Downloads')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('organizadores', models.ManyToManyField(help_text='Selecione os organizadores desta publicação', related_name='publicacoes', to='publicacoes.organizador', verbose_name='Organizadores')),
            ],
            options={
                'verbose_name': 'Publicação PDF',
                'verbose_name_plural': 'Publicações PDF',
                'ordering': ['-ano_publicacao', '-criado_em'],
                'indexes': [models.Index(fields=['ano_publicacao'], name='publicacoes_ano_pub_b27a5d_idx'), models.Index(fields=['categoria'], name='publicacoes_categor_8c8f28_idx'), models.Index(fields=['ativa'], name='publicacoes_ativa_c1dfd4_idx'), models.Index(fields=['destaque'], name='publicacoes_destaqu_fd47b1_idx')],
            },
        ),
    ]
