# Generated by Django 5.2 on 2025-08-25 22:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Álbum')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('cover_image', models.ImageField(upload_to='galeria/covers/', verbose_name='Imagem de Capa')),
                ('event_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbuns',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galeria/photos/', verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Legenda')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='galeria.album', verbose_name='Álbum')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
